Use GCC 9 because there are some problems with 10
```
blksrc.cc: In constructor 'Block::Block(const Seq*, INT, bool)':
  blksrc.cc:400:2: error: 'prelude' was not declared in this scope
    400 |  prelude = max_width() * (istron? 3: 1) - 1;
        |  ^~~~~~~
  blksrc.cc:404:2: error: 'margin' was not declared in this scope
    404 |  margin = prelude;
        |  ^~~~~~
```

Replace all usages of __aarch64__ with __ARM_NEON

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>